title: "Shad0wCrux Dashboard"
description: "SOC Monitoring Interface (Static Demo)"
baseurl: ""
url: "https://shad0wcrux.github.io"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md

